<div class="page-header"><div class="page-header-left"><h2>Edit Vehicle — ABC-1234</h2><p>Toyota Hi-Ace 2022</p></div><a href="<?= Helpers::url('/vehicles') ?>" class="btn btn-outline">← Back</a></div>
<form method="POST" action="<?= Helpers::url('/vehicles/1/edit') ?>"><div class="form-card">
<div class="form-section-title">Vehicle Information</div>
<div class="form-row"><div class="form-group"><label class="form-label">Plate Number</label><input type="text" class="form-input" name="plate_number" value="ABC-1234"></div><div class="form-group"><label class="form-label">Category</label><select class="form-select" name="category_id"><option selected>Van</option><option>Truck</option><option>Pickup</option></select></div></div>
<div class="form-row-3 form-row"><div class="form-group"><label class="form-label">Brand</label><input type="text" class="form-input" name="brand" value="Toyota"></div><div class="form-group"><label class="form-label">Model</label><input type="text" class="form-input" name="model" value="Hi-Ace"></div><div class="form-group"><label class="form-label">Year Model</label><input type="number" class="form-input" name="year_model" value="2022"></div></div>
<div class="form-row"><div class="form-group"><label class="form-label">Color</label><input type="text" class="form-input" name="color" value="White"></div><div class="form-group"><label class="form-label">Fuel Type</label><select class="form-select" name="fuel_type"><option value="diesel" selected>Diesel</option><option value="gasoline">Gasoline</option></select></div></div>
<div class="form-section-title">Status & Odometer</div>
<div class="form-row"><div class="form-group"><label class="form-label">Current Odometer (km)</label><input type="number" class="form-input" name="current_odometer_km" value="12450" step="0.01"><p class="form-hint">Updated automatically when trips complete</p></div><div class="form-group"><label class="form-label">Status</label><select class="form-select" name="status"><option value="available">Available</option><option value="on_trip" selected>On Trip</option><option value="under_maintenance">Under Maintenance</option><option value="retired">Retired</option></select></div></div>
<div class="form-group"><label class="form-label">Gross Weight — GVWR (kg)</label><input type="number" class="form-input" name="gross_weight_kg" value="3500" step="0.01"><p class="form-hint">LTO weight coding compliance</p></div>
<div class="form-actions"><button type="submit" class="btn btn-solid">Save Changes</button><a href="<?= Helpers::url('/vehicles') ?>" class="btn btn-outline">Cancel</a></div>
</div></form>