<div class="page-header"><div class="page-header-left"><h2>Add User</h2></div><a href="<?= Helpers::url('/users') ?>" class="btn btn-outline">← Back</a></div>
<form method="POST" action="<?= Helpers::url('/users/create') ?>"><div class="form-card">
<div class="form-section-title">Account Information</div>
<div class="form-row"><div class="form-group"><label class="form-label">First Name <span class="required">*</span></label><input type="text" class="form-input" name="first_name" required></div><div class="form-group"><label class="form-label">Last Name <span class="required">*</span></label><input type="text" class="form-input" name="last_name" required></div></div>
<div class="form-row"><div class="form-group"><label class="form-label">Email <span class="required">*</span></label><input type="email" class="form-input" name="email" required></div><div class="form-group"><label class="form-label">Employee ID</label><input type="text" class="form-input" name="employee_id" placeholder="e.g. EMP-0099"></div></div>
<div class="form-row"><div class="form-group"><label class="form-label">Password <span class="required">*</span></label><input type="password" class="form-input" name="password" required></div><div class="form-group"><label class="form-label">Phone Number</label><input type="text" class="form-input" name="phone_number"></div></div>
<div class="form-section-title">Role & Assignment</div>
<div class="form-row"><div class="form-group"><label class="form-label">Role <span class="required">*</span></label><select class="form-select" name="role" required><option value="">— Select Role —</option><option value="admin">Admin</option><option value="employee">Employee</option><option value="driver">Driver</option></select></div><div class="form-group"><label class="form-label">Company <span class="required">*</span></label><select class="form-select" name="company_id" required><option value="">— Select —</option><option value="1">Remix Construction</option><option value="2">Ideal Home</option><option value="3">TenBuild</option></select></div></div>
<div class="form-group"><label class="form-label">Department</label><select class="form-select" name="department_id"><option value="">— (not required for drivers) —</option><option>Engineering</option><option>Operations</option><option>Logistics</option><option>Admin</option></select></div>
<div class="form-actions"><button type="submit" class="btn btn-solid">Create User</button><a href="<?= Helpers::url('/users') ?>" class="btn btn-outline">Cancel</a></div>
</div></form>